name: Static Analysis
on: [push]

jobs:
  lint:
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        node: ['16']
        os: ['ubuntu-latest']
    steps:
      - uses: actions/checkout@v2

      - name: Setup node ${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{matrix.node}}
          cache: 'npm'

      - run: npm ci
      - run: npm run lint

  format:
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        node: ['16']
        os: ['ubuntu-latest']
    steps:
      - uses: actions/checkout@v2
      - name: Setup node ${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{matrix.node}}
          cache: 'npm'

      - run: npm ci
      - run: npx nx format:check --all && npm run format:check
